struct CCollisionActorManager {
  rstl::vector<CJointCollisionDescription> jointDescriptions = mJointDescriptions.mCount
  u16 ownerId = mOwnerId
  bool active = mActive
  bool destroyed = mDestroyed
  bool movable = mMovable
}

struct CJointCollisionDescription {
  size 0x44
  ECollisionType colType = mColType
  EOrientationType orientType = mOrientType
  CSegId pivotId = mPivotId
  CSegId nextId = mNextId
  CVector3f bounds = mBounds
  CVector3f _pivotPoint = mPivotPoint
  f32 radius = mRadius
  f32 maxSeparation = mMaxSeparation
  *u8 _name = mName.mPtr
  u16 actorId = mActorId
  f32 mass = mMass
}

enum ECollisionType {
  Sphere=0,
  SphereSubdivide,
  AABox,
  OBBAutoSize,
  OBB,
}

enum EOrientationType { Zero=0, One }

struct CSegId {
  u8 segId = mId
}