struct CScriptTrigger: CActor {
    ETriggerFlags triggerFlags = mFlags
    bool detectPlayer = mFlags:0:1
    bool detectAI = mFlags:1:1
    bool detectProjectiles1 = mFlags:2:1
    bool detectProjectiles2 = mFlags:3:1
    bool detectProjectiles3 = mFlags:4:1
    bool detectProjectiles4 = mFlags:5:1
    bool detectBombs = mFlags:6:1
    bool detectPowerBombs = mFlags:7:1
    bool detectProjectiles5 = mFlags:8:1
    bool detectProjectiles6 = mFlags:9:1
    bool detectProjectiles7 = mFlags:10:1
    bool killOnEnter = mFlags:11:1
    bool detectMorphedPlayer = mFlags:12:1
    bool useCollisionImpulses = mFlags:13:1
    bool detectCamera = mFlags:14:1
    bool useBooleanIntersection = mFlags:15:1
    bool detectUnmorphedPlayer = mFlags:16:1
    bool blockEnvironmentalEffects = mFlags:17:1
    CAABB bounds = mBounds
}

enum ETriggerFlags: u32 {
  None = 0,
  DetectPlayer = 0x1,
  DetectAI = 0x2,
  DetectProjectiles1 = 0x4,
  DetectProjectiles2 = 0x8,
  DetectProjectiles3 = 0x10,
  DetectProjectiles4 = 0x20,
  DetectBombs = 0x40,
  DetectPowerBombs = 0x80,
  DetectProjectiles5 = 0x100,
  DetectProjectiles6 = 0x200,
  DetectProjectiles7 = 0x400,
  KillOnEnter = 0x800,
  DetectMorphedPlayer = 0x1000,
  UseCollisionImpulses = 0x2000,
  DetectCamera = 0x4000,
  UseBooleanIntersection = 0x8000,
  DetectUnmorphedPlayer = 0x10000,
  BlockEnvironmentalEffects = 0x20000
}