struct CScriptCoverPoint: CActor {
    bool landHere = mFlags:29:1
    bool wallHang = mFlags:28:1
    bool stay = mFlags:27:1
    bool unknown1 = mFlags:26:1
    bool attackDirection = mFlags:25:1
    bool unknown2 = mFlags:24:1

    f32 cosHorizontalAngle = mCosHorizontalAngle
    f32 sinVerticalAngle = mSinVerticalAngle
    f32 coverTime = mCoverTime

    bool crouch = mCrouch
    bool inUse = mInUse

    f32 timeLeft = mTimeLeft
}
