struct CScriptDoor: CPhysicsActor {

  f32 animLength = mAnimLength
  f32 animTime = mAnimTime
  EDoorAnimType doorAnimState = mDoorState
  CAABB touchBounds = x264_
  u16 partner1 = mPartner1
  u16 partner2 = mPartner2
  u16 prevDoor = mPrevDoor
  u16 dockId = mDockId
  CAABB modelBounds = mModelBounds
  CVector3f orbitPos = mOrbitPos

  //u8 flags 0x2A8
  bool closing = mClosing
  bool wasOpen = mWasOpen
  bool isOpen = mIsOpen
  bool conditionsMet = mConditionsMet
  bool projectilesCollide = mProjectilesCollide
  bool ballDoor = mBallDoor
  bool doClose = mDoClose
}

enum EDoorAnimType {
    Open = 0, Close, Ready
}
