struct CBeamProjectile: CGameProjectile {

}

struct CElectricBeamProjectile: CGameProjectile {

}

struct CEnergyProjectile: CGameProjectile {

}

struct CFlaahgraProjectile: CGameProjectile {

}

struct CFlameThrower: CGameProjectile {

}

struct CMetroidPrimeProjectile: CGameProjectile {

}

struct CNewFlameThrower: CGameProjectile {

}

struct CPlasmaProjectile: CGameProjectile {

}

struct CTargetableProjectile: CGameProjectile {

}

struct CWaveBuster: CGameProjectile {

}


struct CGameProjectile: CWeapon {
  bool projectileActive = mActive
  f32 projExtent = mProjExtent
  CProjectileWeapon projectile = mProjectile
  CVector3f previousPos = mPreviousPos
}

struct CProjectileWeapon {
  CTransform localToWorldXf = mLocalToWorldXf
  CTransform localXf = mLocalXf
  CVector3f worldOffset = mWorldOffset
  CVector3f localOffset = mLocalOffset
  CVector3f projOffset = mProjOffset
  CVector3f scale = mScale
  CVector3f localOffset2 = mLocalOffset2
  CVector3f velocity = mVelocity
  CVector3f gravity = mGravity

  i32 lifetime = mLifetime
  f64 curTime = mCurTime
  f64 remainderTime = mRemainderTime

}

struct CWeapon: CActor {
    EWeaponType weaponType = mWeaponType
}

enum EWeaponType {
  None = -1,
  Power = 0,
  Ice = 1,
  Wave = 2,
  Plasma = 3,
  Bomb = 4,
  PowerBomb = 5,
  Missile = 6,
  BoostBall = 7,
  Phazon = 8,
  AI = 9,
  PoisonWater = 10,
  Lava = 11,
  Heat = 12,
  Unused1 = 13,
  OrangePhazon = 14
}