struct CModelData {
    CVector3f scale = mScale
    bool ownsAnimData = mAnimData.mHas
    *CAnimData animData = mAnimData.mItem
    //TODO: bitstruct
    //x14_24 renderSorted
    //x14_25 sortThermal
    u32 flags 0x14
    CColor ambientColor = mAmbientColor
    TLockedToken<CModel> normalModel = mNormalModel
    TLockedToken<CModel> xrayModel = mXrayModel
    TLockedToken<CModel> infraModel = mInfraModel
    // TLockedToken<CModel> xrayModel 0x34
    // TLockedToken<CModel> infraModel 0x44
}