struct CPlayer: CPhysicsActor {
    EPlayerMovementState jumpstate = mMovementState
    f32 sjTimer = mSjTimer
    f32 startingJumpTimeout = mStartingJumpTimeout
    f32 minJumpTimeout = mMinJumpTimeout
    i32 jumpPresses = mJumpPresses
    ESurfaceRestraints surfaceRestraint = mSurfaceRestraint
    CAABB fpBounds = mFpBounds
    EPlayerCameraState cameraState = mCameraState
    EPlayerMorphBallState morphState = mMorphBallState
    EPlayerMorphBallState spawnedMorphBallState = mSpawnedMorphBallState
    f32 fallingTime = mFallingTime
    EPlayerOrbitState orbitState = mOrbitState
    EPlayerOrbitType orbitType = mOrbitType
    EPlayerOrbitRequest orbitRequest = mOrbitBrokenType
    CVector3f orbitPoint = mOrbitPoint
    CVector3f orbitVector = mOrbitVector
    EPlayerZoneInfo orbitZoneMode = mOrbitZoneMode
    EPlayerZoneType orbitType = mOrbitZoneType
    bool orbitLockEstablished = mOrbitLockEstablished
    bool sidewaysDashing = mSidewaysDashing
    f32 strafeInputAtDash = mStrafeInputAtDash
    f32 dashTimer = mDashTimer
    f32 dashButtonHoldTime = mDashButtonHoldTime
    bool doneSidewaysDashing = mDoneSidewaysDashing
    f32 dashSpeedMultiplier = mDashSpeedMultiplier
    EPlayerScanState scanState = mScanState
    f32 scanningTime = mScanningTime
    f32 curScanTime = mCurScanTime
    EGrappleState grappleState = mGrappleState
    f32 grappleSwingTimer = mGrappleSwingTimer
    CVector3f grappleSwingAxis = mGrappleSwingAxis
    // TODO: std::unique_ptr<CFailsafeTest> x4a0_failsafeTest;
    // TODO: TReservedAverage<float, 20> x4a4_moveSpeedAvg
    f32 moveSpeed = mMoveSpeed
    f32 flatMoveSpeed = mFlatMoveSpeed
    CVector3f lookDir = mLookDir
    CVector3f moveDir = mMoveDir
    CVector3f leaveMorphDir = mLeaveMorphDir
    CVector3f lastPosForDirCalc = mLastPosForDirCalc
    CVector3f gunDir = mGunDir
    f32 frozenTimeout = mFrozenTimeout
    i32 iceBreakJumps = mIceBreakJumps
    i32 additionalIceBreakJumps = mAdditionalIceBreakJumps
    bool controlsFrozen = mControlsFrozen
    f32 controlsFrozenTimeout = mControlsFrozenTimeout
    f32 eyeZBias = mEyeZBias
    u32 bombJumpCount = mBombJumpCount
    i32 bombJumpCheckDelayFrames = mBombJumpCheckDelayFrames


    *CPlayerGun gun = mGun
    *CMorphBall morphBall = mMorphball
    *CPlayerCameraBob cameraBob = mCameraBob

    bool visorChangeRequested = mVisorChangeRequested
    bool showCrosshairs = mShowCrosshairs
    bool canEnterMorphBall = mCanEnterMorphBall
    bool canLeaveMorphBall = mCanLeaveMorphBall
    bool spiderBallControlXY = mSpiderBallControlXY
    bool controlDirOverride = mControlDirOverride
    bool inWaterMovement = mInWaterMovement
    bool splashUpdated = mSplashUpdated
    bool camSubmerged = mCamSubmerged
    bool slidingOnWall = mSlidingOnWall
    bool hitWall = mHitWall
    bool selectFluidBallSound = mSelectFluidBallSound
    bool stepCameraZBiasDirty = mStepCameraZBiasDirty
    bool extendTargetDistance = mExtendTargetDistance
    bool interpolatingControlDir = mInterpolatingControlDir
    bool outOfBallLookAtHint = mOutOfBallLookAtHint
    bool aimingAtProjectile = mAimingAtProjectile
    bool aligningGrappleSwingTurn = mAligningGrappleSwingTurn
    bool disableInput = mDisableInput
    bool newScanScanning = mNewScanScanning
    bool overrideRadarRadius = mOverrideRadarRadius
    bool noDamageLoopSfx = mNoDamageLoopSfx
    bool outOfBallLookAtHintActor = mOutOfBallLookAtHintActor
}

enum EPlayerMovementState: u32 {
    OnGround=0, Jump, ApplyJump, Falling, FallingMorphed
}

enum EPlayerMorphBallState: u32 { Unmorphed, Morphed, Morphing, Unmorphing }

enum EPlayerCameraState: u32 { FirstPerson, Ball, Two, Transitioning, Spawned }

enum  EPlayerOrbitState: u32 {
    NoOrbit, OrbitObject, OrbitPoint, OrbitCarcass, ForcedOrbitObject, Grapple
}

enum EPlayerOrbitType: u32 { Close, Far, Default }
enum EPlayerOrbitRequest: u32 {
    StopOrbit, Respawn, EnterMorphBall, Default, Four, Five, InvalidateTarget,
    BadVerticalAngle, ActivateOrbitSource, ProjectileCollide, Freeze,
    DamageOnGrapple, LostGrappleLineOfSight
}

enum EPlayerZoneInfo: u32 { Targeting, Scan }

enum EPlayerZoneType: u32 { Always = -1, Box = 0, Ellipse }

enum EPlayerScanState: u32 { NotScanning, Scanning, ScanComplete }

enum EGrappleState: u32 { None, Firing, Pull, Swinging, JumpOff }

enum ESurfaceRestraints: u32 { Normal, Air, Ice, Organic, Water, Lava, Phazon, Shrubbery }