#!/usr/bin/env python3
"""Regenerates prime_defs/symbols/<VERSION>.txt from prime-decomp's symbols.txt.

Keeps every named data object (vtables, globals, statics); drops functions and
the decomp's auto-generated names (lbl_*, @NNN, ...). Aliases from
tools/symbol_aliases.txt are added under their own name.

Usage: tools/gen_symbols.py <path/to/prime-decomp> <VERSION>...
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LINE = re.compile(r"^(\S+) = (\.\w+):0x([0-9A-Fa-f]+); // (.*)$")
AUTO_NAME = re.compile(r"^(lbl_|@|jumptable_|gap_|\.\.\.)")


def load_aliases(version):
  aliases = []
  for line in (ROOT / "tools/symbol_aliases.txt").read_text().splitlines():
    line = line.split("#", 1)[0].strip()
    if not line:
      continue
    v, name, target = line.split()
    if v == version:
      aliases.append((name, target))
  return aliases


def generate(decomp, version):
  by_name = {}
  kept = []
  for line in (decomp / "config" / version / "symbols.txt").read_text().splitlines():
    m = LINE.match(line)
    if not m:
      continue
    name, section, addr, attrs = m.groups()
    addr = int(addr, 16)
    by_name[name] = addr
    if "type:object" in attrs and section != ".text" and not AUTO_NAME.match(name):
      kept.append((name, addr))

  names = {n for n, _ in kept}
  for name, target in load_aliases(version):
    if target not in by_name:
      sys.exit(f"{version}: alias {name} -> {target}: no such symbol")
    if name in names:
      sys.exit(f"{version}: alias {name} is already a decomp symbol; drop the alias")
    kept.append((name, by_name[target]))

  kept.sort(key=lambda s: (s[1], s[0]))
  out = ROOT / "prime_defs/symbols" / f"{version}.txt"
  out.parent.mkdir(parents=True, exist_ok=True)
  with out.open("w") as f:
    f.write(f"# Generated by tools/gen_symbols.py from prime-decomp config/{version}/symbols.txt\n")
    for name, addr in kept:
      f.write(f"0x{addr:08X} {name}\n")
  print(f"wrote {out} ({len(kept)} symbols)")


def main():
  if len(sys.argv) < 3:
    sys.exit(f"usage: {sys.argv[0]} <prime-decomp> <VERSION>...")
  decomp = Path(sys.argv[1])
  for version in sys.argv[2:]:
    generate(decomp, version)


if __name__ == "__main__":
  main()
