struct CAreaOctTree {
    CAABB aabb 0x0
    CAreaOctTree::Node::ETreeType treeType 0x18
    *u8 buf 0x1C
    *u8 treebuff 0x20
    u32 matCount 0x24
    *u32 materials 0x28
    *u8 vertMats 0x2C
    *u8 edgeMats 0x30
    *u8 polyMats 0x34
    u32 edgeCount 0x38
    *CCollisionEdge edges 0x3C
    u32 polyCount 0x40
    *u16 polyEdges 0x44
    u32 vertCount 0x48
    *f32 verts 0x4C
}

struct CAreaOctTree::Node {
    CAABB aabb 0x0
    *u8 ptr 0x18 // not sure what this is
    *CAreaOctTree owner 0x1C
    CAreaOctTree::Node::ETreeType nodeType 0x20
}

enum CAreaOctTree::Node::ETreeType { 
    Invalid, 
    Branch, 
    Leaf
}

struct CCollisionEdge {
    u16 edge1 0x0
    u16 edge2 0x2
}

enum CollisionMaterial: u32 {
  NO_STEP_LOGIC = 0x1,
  STONE = 0x2,
  METAL = 0x4,
  GRASS = 0x8,
  ICE = 0x10,
  PILLAR = 0x20,
  METAL_GRATING = 0x40,
  PHAZON = 0x80,
  DIRT = 0x100,
  LAVA = 0x200,
  LAVA_STONE = 0x400,
  SNOW = 0x800,
  MUD_SLOW = 0x1000,
  HALF_PIPE = 0x2000,
  MUD = 0x4000,
  GLASS = 0x8000,
  SHIELD = 0x10000,
  SAND = 0x20000,
  PROJECTILE_PASSTHROUGH = 0x40000,
  SOLID = 0x80000,
  NO_PLATFORM_COLLISION = 0x100000,
  CAMERA_PASSTHROUGH = 0x200000,
  WOOD = 0x400000,
  ORGANIC = 0x800000,
  NO_EDGE_COLLISION = 0x1000000,
  REDUNDANT_EDGE_OR_FLIPPED_TRI = 0x2000000,
  SEE_THROUGH = 0x4000000,
  SCAN_PASSTHROUGH = 0x8000000,
  AI_PASSTHROUGH = 0x10000000,
  CEILING = 0x20000000,
  WALL = 0x40000000,
  FLOOR = 0x80000000
}