struct CAreaOctTree {
    CAABB aabb = mAabb
    CAreaOctTree::Node::ETreeType treeType = mTreeType
    *u8 buf = mBuf
    *u8 treebuff = mTreeBuf
    u32 matCount = mMatCount
    *u32 materials = mMaterials
    *u8 vertMats = mVertMats
    *u8 edgeMats = mEdgeMats
    *u8 polyMats = mPolyMats
    u32 edgeCount = mEdgeCount
    *CCollisionEdge edges = mEdges
    u32 polyCount = mPolyCount
    *u16 polyEdges = mPolyEdges
    u32 vertCount = mVertCount
    *f32 verts = mVerts
}

struct CAreaOctTree::Node {
    CAABB aabb = mAabb
    *u8 ptr = mPtr // not sure what this is
    *CAreaOctTree owner = mOwner
    CAreaOctTree::Node::ETreeType nodeType = mNodeType
}

enum CAreaOctTree::Node::ETreeType { 
    Invalid, 
    Branch, 
    Leaf
}

struct CCollisionEdge {
    u16 edge1 = mIndex1
    u16 edge2 = mIndex2
}

enum CollisionMaterial: u32 {
  NO_STEP_LOGIC = 0x1,
  STONE = 0x2,
  METAL = 0x4,
  GRASS = 0x8,
  ICE = 0x10,
  PILLAR = 0x20,
  METAL_GRATING = 0x40,
  PHAZON = 0x80,
  DIRT = 0x100,
  LAVA = 0x200,
  LAVA_STONE = 0x400,
  SNOW = 0x800,
  MUD_SLOW = 0x1000,
  HALF_PIPE = 0x2000,
  MUD = 0x4000,
  GLASS = 0x8000,
  SHIELD = 0x10000,
  SAND = 0x20000,
  PROJECTILE_PASSTHROUGH = 0x40000,
  SOLID = 0x80000,
  NO_PLATFORM_COLLISION = 0x100000,
  CAMERA_PASSTHROUGH = 0x200000,
  WOOD = 0x400000,
  ORGANIC = 0x800000,
  NO_EDGE_COLLISION = 0x1000000,
  REDUNDANT_EDGE_OR_FLIPPED_TRI = 0x2000000,
  SEE_THROUGH = 0x4000000,
  SCAN_PASSTHROUGH = 0x8000000,
  AI_PASSTHROUGH = 0x10000000,
  CEILING = 0x20000000,
  WALL = 0x40000000,
  FLOOR = 0x80000000
}