enum EPhase {
  LoadHeader,
  LoadSecSizes,
  ReserveSections,
  LoadDataSections,
  WaitForFinish
}

enum EChain {
  Invalid = -1,
  ToDeallocate,
  Deallocated,
  Loading,
  Alive,
  AliveJudgement
}

enum EOcclusionState {
  Occluded,
  Visible
}

struct SDockReference {
  u32 area = mArea
  i16 dock = mDock
  bool loadOther = mLoadOther
}

struct CGameArea::Dock {
  size 0x4C
  i32 referenceCount 0x0
  u32 dockCount 0x8
  rstl::vector<SDockReference> dockReferences 0x8
}

struct CGameArea {
  size 0x13c
  u32 vtable = __vptr$
  u32 selfIDX = mSelfIdx
  u32 nameStrg = mNameSTRG
  CTransform transform = mTransform
  CAABB aabb = mAabb
  u32 mrea = mMrea
  u32 areaID = mAreaId
  rstl::vector<u16> attachedAreaIndices = mAttachedAreaIndices.mCount
  rstl::vector<CGameArea::Dock> docks = mDocks.mCount
  // TODO: bit struct
  u32 flags 0xF0
  bool isPostConstructed = mPostConstructedFlag
  bool active = mActive
  bool tokensReady = mTokensReady
  bool loadPaused = mLoadPaused
  bool validated = mValidated
  EPhase phase = mPhase
  u32 loadTransactions 0xF8
  EChain curChain = mCurChain
  *CPostConstructed postConstructed = mPostConstructed
}