struct CMain {
  EFlowState flowState = mRestartMode
  bool finished = mFinished
  bool mfGameBuilt = mMfGameBuilt
  bool screenFading = mScreenFading
  bool manageCard = mManageCard
  bool cardBusy = mCardBusy
  bool gameFrameDrawn = mGameFrameDrawn

  *CGameGlobalObjects globalObjects = mGameGlobalObjects
}

enum EFlowState: u32 {
  None,
  WinBad,
  WinGood,
  WinBest,
  LoseGame,
  Default,
  StateSetter,
}