struct CObjectList {
    SObjectListEntry[1024] list = mObjects
    EGameObjectList typeEnum = mListType
    u16 firstID = mFirstId
    u16 size = mCount
}

struct SObjectListEntry {
    size 0x8
    *CEntity entity = mEnt
    u16 next = mNext
    u16 prev = mPrev
}

enum EGameObjectList {
  Invalid = -1,
  All,
  Actor,
  PhysicsActor,
  GameCamera,
  GameLight,
  ListeningAi,
  AiWaypoint,
  PlatformAndDoor,
}