struct CResFactory {
    CResLoader loader = mResLoader
    CFactoryMgr factoryManager = mFactoryMgr
    rstl::list<SLoadingData> loadList = mLoadList.mEnd
}

struct CResLoader {

}

struct CFactoryMgr {

}

struct SLoadingData {
    SObjectTag tag = mTag
    rstl::autoptr<IDvdRequest> dvdReq = mDvdReq
    *IObj targetPtr = mTarget
    *u8 loadBuffer = mBuffer.mItem
    u32 resLen = mSize
    u32 compressed = mCompression
    //CVParamTransfer cvXfer 0x34
}

struct IDvdRequest {

}