struct CStateManager {
    // `mObjectLists[kOL_All].mItem`: the storage is untyped bytes of 8-byte `auto_ptr`s.
    *CObjectList allObjects = mObjectLists.mData[4]
    *CPlayer player = mPlayer
    *CWorld world = mWorld
    *CCameraManager cameraManager = mCameraManager
    rstl::rc_ptr<CPlayerState> playerState = mPlayerState
    u32 nextAreaID = mNextAreaId
    u32 prevAreaID = mPrevAreaId
    CRandom16 random = mRandomValue

    bool readyToRender = mReadyToRender
    bool quitGame = mQuitGame
    bool generatingObject = mGeneratingObject
    bool inMapScreen = mInMapScreen
    bool inSaveUI = mInSaveUI
    bool cinematicPause = mCinematicPause
    bool fullThreat = mFullThreat
}