struct TLockedToken<T>: CToken {
    *T _obj
}

struct TCachedToken<T>: CToken {
    *T _obj
}

struct TToken<T>: CToken {
    
}

struct CToken {
    *CObjectReference ref = mObjRef
    u32 held = mLockHeld_init
}

struct CObjectReference {
    u16 refCount 0x0
    u16 lockCount 0x2
    bool loading = mLoading
    SObjectTag objTag = mObjTag
    *IObjectStore objectStore = mObjectStore
    u32 obj_ptr = mObject
    *IObj obj = mObject
    //CVParamTransfer params 0x1
}