struct CTweakPlayer {
    u32 vtable = __vptr$
    f32[8] maxTranslationalAcceleration = mMaxTranslationalAcceleration
    f32[8] maxRotationalAcceleration = mMaxRotationalAcceleration
    f32[8] translationFriction = mTranslationFriction
    f32[8] rotationFriction = mRotationFriction
    f32[8] rotationMaxSpeed = mRotationMaxSpeed
    f32[8] translationMaxSpeed = mTranslationMaxSpeed
    f32 normalGravAccel = mNormalGravAccel
    f32 fluidGravAccel = mFluidGravAccel
    f32 verticalJumpAccel = mVerticalJumpAccel
    f32 horizontalJumpAccel = mHorizontalJumpAccel
    f32 verticalDoubleJumpAccel = mVerticalDoubleJumpAccel
    f32 horizontalDoubleJumpAccel = mHorizontalDoubleJumpAccel
    f32 waterJumpFactor = mWaterJumpFactor
    f32 waterBallJumpFactor = mWaterBallJumpFactor
    f32 lavaJumpFactor = mLavaJumpFactor
    f32 lavaBallJumpFactor = mLavaBallJumpFactor
    f32 phazonJumpFactor = mPhazonJumpFactor
    f32 phazonBallJumpFactor = mPhazonBallJumpFactor
    f32 allowedJumpTime = mAllowedJumpTime
    f32 allowedDoubleJumpTime = mAllowedDoubleJumpTime
    f32 minDoubleJumpWindow = mMinDoubleJumpWindow
    f32 maxDoubleJumpWindow = mMaxDoubleJumpWindow
//    f32  0x104
    f32 minJumpTime = mMinJumpTime
    f32 minDoubleJumpTime = mMinDoubleJumpTime
    f32 allowedLedgeTime = mAllowedLedgeTime
    f32 doubleJumpImpulse = mDoubleJumpImpulse
    f32 backwardsForceMultiplier = mBackwardsForceMultiplier
    f32 bombJumpRadius = mBombJumpRadius
    f32 bombJumpHeight = mBombJumpHeight
    f32 eyeOffset = mEyeOffset
    f32 turnSpeedMultiplier = mTurnSpeedMultiplier
    f32 freeLookTurnSpeedMultiplier = mFreeLookTurnSpeedMultiplier
    f32 horizontalFreeLookAngleVel = mHorizontalFreeLookAngleVel
    f32 verticalFreeLookAngleVel = mVerticalFreeLookAngleVel
    f32 freeLookSpeed = mFreeLookSpeed
    f32 freeLookSnapSpeed = mFreeLookSnapSpeed
//    f32  0x140
    f32 freeLookCenteredThresholdAngle = mFreeLookCenteredThresholdAngle
    f32 freeLookCenteredTime = mFreeLookCenteredTime
    f32 freeLookDampenFactor = mFreeLookDampenFactor
    f32 leftDiv = mLeftDiv
    f32 rightDiv = mRightDiv
    f32[3] orbitMinDistance = mOrbitMinDistance
    f32[3] orbitNormalDistance = mOrbitNormalDistance
    f32[3] orbitMaxDistance = mOrbitMaxDistance
//    f32  0x17c
    f32 orbitModeTimer = mOrbitModeTimer
    f32 orbitCameraSpeed = mOrbitCameraSpeed
    f32 orbitUpperAngle = mOrbitUpperAngle
    f32 orbitLowerAngle = mOrbitLowerAngle
    f32 orbitHorizAngle = mOrbitHorizAngle
//    f32  0x194
//    f32  0x198
    f32 orbitMaxTargetDistance = mOrbitMaxTargetDistance
    f32 orbitMaxLockDistance = mOrbitMaxLockDistance
    f32 orbitDistanceThreshold = mOrbitDistanceThreshold
    u32[2] orbitScreenBoxHalfExtentX = mOrbitScreenBoxHalfExtentX
    u32[2] orbitScreenBoxHalfExtentY = mOrbitScreenBoxHalfExtentY
    u32[2] orbitScreenBoxCenterX = mOrbitScreenBoxCenterX
    u32[2] orbitScreenBoxCenterY = mOrbitScreenBoxCenterY
    u32[2] orbitZoneIdealX = mOrbitZoneIdealX
    u32[2] orbitZoneIdealY = mOrbitZoneIdealY
    f32 orbitNearX = mOrbitNearX
    f32 orbitNearZ = mOrbitNearZ
//    f32  0x1e0
//    f32  0x1e4
    f32 orbitFixedOffsetZDiff = mOrbitFixedOffsetZDiff
    f32 orbitZRange = mOrbitZRange
//    f32  0x1f0
//    f32  0x1f4
//    f32  0x1f8
    f32 orbitPreventionTime = mOrbitPreventionTime
////    bool x200_24_dashEnabled : 1{};
////    bool x200_25_dashOnButtonRelease : 1{};
    f32 dashButtonHoldCancelTime = mDashButtonHoldCancelTime
    f32 dashStrafeInputThreshold = mDashStrafeInputThreshold
    f32 sidewaysDoubleJumpImpulse = mSidewaysDoubleJumpImpulse
    f32 sidewaysVerticalDoubleJumpAccel = mSidewaysVerticalDoubleJumpAccel
    f32 sidewaysHorizontalDoubleJumpAccel = mSidewaysHorizontalDoubleJumpAccel
    f32 scanningRange = mScanningRange
//    bool x21c_24_scanRetention : 1{};
//    bool x21c_25_scanFreezesGame : 1{};
//    bool x21c_26_orbitWhileScanning : 1{};
    f32 scanMaxTargetDistance = mScanMaxTargetDistance
    f32 scanMaxLockDistance = mScanMaxLockDistance
//    bool x228_24_freelookTurnsPlayer : 1{};
//    bool x228_25_ : 1{};
//    bool x228_26_ : 1{};
//    bool x228_27_moveDuringFreeLook : 1{};
//    bool x228_28_holdButtonsForFreeLook : 1{};
//    bool x228_29_twoButtonsForFreeLook : 1{};
//    bool x228_30_ : 1{};
//    bool x228_31_ : 1{};
//    bool x229_24_ : 1{};
//    bool x229_25_aimWhenOrbitingPoint : 1{};
//    bool x229_26_stayInFreeLookWhileFiring : 1{};
//    bool x229_27_ : 1{};
//    bool x229_28_ : 1{};
//    bool x229_29_orbitFixedOffset : 1{};
//    bool x229_30_gunButtonTogglesHolster : 1{};
//    bool x229_31_gunNotFiringHolstersGun : 1{};
//    bool x22a_24_fallingDoubleJump : 1{};
//    bool x22a_25_impulseDoubleJump : 1{};
//    bool x22a_26_firingCancelsCameraPitch : 1{};
//    bool x22a_27_assistedAimingIgnoreHorizontal : 1{};
//    bool x22a_28_assistedAimingIgnoreVertical : 1{};
//    f32  0x22c
//    f32  0x230
    f32 aimMaxDistance = mAimMaxDistance
//    f32  0x238
//    f32  0x23c
//    f32  0x240
//    f32  0x244
//    f32  0x248
    f32 aimThresholdDistance = mAimThresholdDistance
//    f32  0x250
//    f32  0x254
    f32 aimBoxWidth = mAimBoxWidth
    f32 aimBoxHeight = mAimBoxHeight
    f32 aimTargetTimer = mAimTargetTimer
    f32 aimAssistHorizontalAngle = mAimAssistHorizontalAngle
    f32 aimAssistVerticalAngle = mAimAssistVerticalAngle
    f32 playerHeight = mPlayerHeight
    f32 playerXYHalfExtent = mPlayerXYHalfExtent
    f32 stepUpHeight = mStepUpHeight
    f32 stepDownHeight = mStepDownHeight
    f32 playerBallHalfExtent = mPlayerBallHalfExtent
    f32 firstPersonCameraSpeed = mFirstPersonCameraSpeed
//    f32  0x284
    f32 jumpCameraPitchDownStart = mJumpCameraPitchDownStart
    f32 jumpCameraPitchDownFull = mJumpCameraPitchDownFull
    f32 jumpCameraPitchDownAngle = mJumpCameraPitchDownAngle
    f32 fallCameraPitchDownStart = mFallCameraPitchDownStart
    f32 fallCameraPitchDownFull = mFallCameraPitchDownFull
    f32 fallCameraPitchDownAngle = mFallCameraPitchDownAngle
    f32 orbitDistanceMax = mOrbitDistanceMax
    f32 grappleSwingLength = mGrappleSwingLength
    f32 grappleSwingPeriod = mGrappleSwingPeriod
    f32 grapplePullSpeedMin = mGrapplePullSpeedMin
    f32 grappleCameraSpeed = mGrappleCameraSpeed
    f32 maxGrappleLockedTurnAlignDistance = mMaxGrappleLockedTurnAlignDistance
    f32 grapplePullSpeedProportion = mGrapplePullSpeedProportion
    f32 grapplePullSpeedMax = mGrapplePullSpeedMax
    f32 grappleLookCenterSpeed = mGrappleLookCenterSpeed
    f32 maxGrappleTurnSpeed = mMaxGrappleTurnSpeed
    f32 grappleJumpForce = mGrappleJumpForce
    f32 grappleReleaseTime = mGrappleReleaseTime
    u32 grappleJumpMode = mGrappleJumpMode
//    bool x2d4_orbitReleaseBreaksGrapple{};
//    bool x2d5_invertGrappleTurn{};
    f32 grappleBeamSpeed = mGrappleBeamSpeed
    f32 grappleBeamXWaveAmplitude = mGrappleBeamXWaveAmplitude
    f32 grappleBeamZWaveAmplitude = mGrappleBeamZWaveAmplitude
    f32 grappleBeamAnglePhaseDelta = mGrappleBeamAnglePhaseDelta
//    f32  0x2e8
//    f32  0x2ec
//    f32  0x2f0
//    bool x2f4_{};
    f32 frozenTimeout = mFrozenTimeout
    u32 iceBreakJumpCount = mIceBreakJumpCount
    f32 variaDamageReduction = mVariaDamageReduction
    f32 gravityDamageReduction = mGravityDamageReduction
    f32 phazonDamageReduction = mPhazonDamageReduction
}