struct CWorld {
    u32 vtable = __vptr$
    CWorld::Phase phase = mPhase
    u32 mlvl = mMlvlId
    u32 strgID = mStrgId
    u32 savewID = mSavwId
    rstl::vector<rstl::autoptr<CGameArea>> areas = mAreas.mCount
    u32 mapwId = mMapwId
    u32 relays 0x2C
    u32 currentArea = mCurAreaId
    u32 flags 0x70
    
}

enum CWorld::Phase {
    Loading,
    LoadingMap,
    LoadingMapAreas,
    LoadingSkyBox,
    LoadingSoundGroups,
    Done,
}